process.env.DATABASE_URL = 'mongodb+srv://test:test@test.tgpeg.mongodb.net/myFirstDatabase?retryWrites=true&w=majority'
process.env.CLOUDINARY_URL = 'cloudinary://634549676984392:ZgCVQWbB3fjb_pNFpeP8A2zzq3o@dede4atest'
process.env.SECRET = 'tokenparatest'
process.env.PASS = 'Admin1Admin2?'
process.env.PASS1='5a29N5wEj3L0'