[[section-introduction-and-goals]]
== Introduccion y metas

[role="arc42help"]
****
Se pretende desarrollar una tienda online utilizando las tecnologías de SOLID y REACT. La tienda permitirá al usuario realizar la compra de cualquiera de los productos disponibles, así como realizar búsquedas entre estos y poder añadirlos a una cesta personal.
****

=== Requisitos generales

[role="arc42help"]
****
La web deberá de cumplir principalmente los siguientes requisitos:

  ·El almacenamiento de los datos deberá de estar separado de la aplicación en si.

  ·La web permitirá al usuario buscar entre los diferentes productos ya sea de manera explícita o a través de filtros de texto.

  ·El administrador del sistema podrá añadir en cualquier momento nuevos productos así como consultar la información de los clientes.

  ·Cada usuario podrá tener su propia cesta personal la cual solo podrá ser consultada por el usuario en cuestión y que perdurará en sesiones posteriores.

  ·Los usuarios tendrán la opción de registrarse dando sus datos personales.

  ·Solo los usuarios registrados tendrán acceso a una cesta personal.

  ·Todos los usuarios tendrán la opción de realizar la devolución de cualquier producto solo con proporcionar el código de la compra. 

****

=== Metas de calidad

[role="arc42help"]
****
Dado que quienes usarán habitualmente la web serán los usuarios y el administrador las metas principales serian:

  ·Usabilidad intuitiva tanto en el caso del administrador como del usuario

  ·Los productos de la tienda han de estar constantemente actualizados (nuevos productos y nuevo stock).

  ·Toda información respecto a los datos de los usuarios como de sus cestas ha de ser privada.

****

=== Stakeholders

[role="arc42help"]
****
Los stakeholders seran los desarrolladores, los usuarios y el profesor
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| Desarrollador | Sergio Murillo | Trabajar con la arquitectura y el código asi como la documentacion y ayudar en la toma de decisiones
| Desarrollador | Pablo Alonso | Trabajar con la arquitectura y el código asi como la documentacion y ayudar en la toma de decisiones
| Desarrollador | Pablo Fernández| Trabajar con la arquitectura y el código asi como la documentacion y ayudar en la toma de decisiones
| Desarrollador | Iker Jiménez | Trabajar con la arquitectura y el código asi como la documentacion y ayudar en la toma de decisiones
| Profesor | Hugo | Supervisar el proyecto
| Usuarios || Usuarios que podran usar libremente la tienda bien sea para realizar una compra o una devolucion o simplemente consultar
|===
