[[section-introduction-and-goals]]
== Introduccion and goals


We intend to develop an online store using SOLID and REACT technologies. The store will allow the user to purchase any of the available products, as well as to search through them and add them to a personal shopping cart.


=== General requirements



The website must mainly meet the following requirements:

* The data storage shall be separated from the application itself.

* The web will allow the user to search among the different products either explicitly or through text filters.

* The system administrator will be able to add new products at any time as well as to consult the information of the clients.

* Each user will be able to have his own personal basket which can only be consulted by the user in question and which will last in subsequent sessions.

* Users will have the option to register by giving their personal data.

* Only registered users will have access to a personal shopping cart.

* All users will have the option to return any product just by providing the purchase code. 





=== Quality goals


Given that those who will habitually use the web will be the users and the administrator, the main goals would be:

[options="header"]
|===
| ID | Priority | Quality | Motivation
| QG1 | 1 | Usability | The application must be intiutive for both administrator and users.
| QG2 | 2 | Availability | The application must be available all time for the users to buy products.
| QG3 | 3 | Privacy and Security | All information regarding the data of users and their carts must be private.
|===


=== Stakeholders

The stakeholders will be the developers, the users and the teachers.


[options="header",cols="1,2"]
|===
| Role | Expectations
| Developers | Work with the architecture and code as well as the documentation and help in decision making.
| Teachers | Overseeing the project
| Clients | Users who will be able to freely use the store either to make a purchase or a return or simply to consult the store.
| Administrator | A special user who will be able to manage the products and client information from the app
|===
