[[section-solution-strategy]]
== Solution Strategy

=== Technologies

These are the technologies we have decided to use:

* MongoDB: NoSQL database.
* TypeScript: JavaScript superset, which mainly adds static typing to JavaScript.
* GitHub: Allows to host Git-based projects.
* SOLID: Project that aims to allow users to decide where their data is stored, in order to improve privacy.
* Libraries
** React: Library for creating user interfaces.
** Node.js: Allows to execute TypeScript on the server side.
** Express: Node.js web application infrastructure.
** Mongoose: Library to connect to the database and add functionality.
** Axios: Library to make async petitions.
** Supertest and Jest: Modules to test our application.
** Programs:
** Visual Studio Code: Code editor that thanks to its large number of extensions will facilitate our work.
** Postman: Software to test APIs.
* Deployment:
** Amazon Web Services: Web server provider where we will deploy our application.
** Docker: Project that automates deployment of applications inside containers. We will create containers for both restapi and webapp to deloy them on AWS.
* APIs:
** Cloudinary: Service that provides an API to upload and download the images of the products.
** Nodemailer: API that allows us to send emails to the user with the details of the orders.
** Shippo: Provides an API to calculate the shipping costs and the estimated day of arrival of the orders.

=== Architectural and design patterns

We have decided to follow the MVC (Model, View and Controller) pattern, which consists of separating the application data
from the logic and the user interface.

=== Decisions to achive quality goals

In order to achieve the proposed objectives we have decided to distribute the work in such a way that part of the group focuses more on
the backend and the other one on the frontend.
We have taken this decision since all the technologies to be used are new for all of us,
and we believe that it will be easier to achieve the objectives if we focus mostly on one part.

* Having half of the group focused on frontend, we believe that it will be easier to to achive the usability goal.
* To achive the availability goal, we will have the application deployed in Amazon Web Services and it will be accesible from everywhere.
* Privacy and Security are another goals that we are focused on. To achive this, the users must have a username and password to access to the application, 
and we are going to use PODs to get the address from the user, so we are not storing any personal information apart from the name, email and DNI.

=== Organizational decisions

In order to work in an organized way and try to minimize errors, we have decided to organize ourselves as follows:

* Creation of three automated dashboards (GitHub Projects), one for each part in which the project is divided.
** Frontend
** Backend
** Documentation
* Creation of several branches:
** master: main branch of the project where stable versions of the project will be uploaded.
** develop: development branch to which the changes made in both frontend and backend will be uploaded by pull request.
** frontend: branch where frontend changes will be uploaded.
** backend: branch where backend changes will be uploaded.
** We will create branches to try things like deploying the application or adding risky features.
** An individual branch for each developer to work on:
*** iker
*** pabloa
*** pablof
*** sergio
* To communicate and make easier the organization we will use:
** Microsoft Teams: We will meet weekly to make decisions.
** WhatsApp: We will use it to make a quick comment, such as to warn of a sudden problem or things that come up.
** GitHub: Here we will communicate through issues and the project board, where we will share tasks.
