[[section-runtime-view]]

== Runtime View
 
.Contents

This section shows the main sequence diagrams between the users and the application.


=== Products catalog

This view shows a request from a customer to view the product catalog. The web receives the request where it will access the database to get the list of products. Once obtained, it returns them to the customer.

[plantuml,"PresentationOfTheProductCatalog",png]
----
@startuml
actor Client
participant Frontend
participant Cloudinary
participant Backend
database MongoDB
Client -> Frontend: Access to products catalog
Frontend -> Backend: Request product list
Backend -> MongoDB: Ask for the list of products
MongoDB --> Backend: Get the list of products
Backend --> Frontend: Send the list of products
Frontend -> Cloudinary: Request for the image of the product
Cloudinary --> Frontend: Sends the image of the product
Frontend --> Client: Get the catalog
@enduml
----


=== Login

This view shows the login process. The website receives the user's credentials, and after a back-end petition the credentials will be verified and the user will be allowed to buy products.

[plantuml,"LoginView",png]
----
@startuml
actor Client
participant Frontend
participant Backend
database MongoDB
Client -> Frontend: Enter credentials
Frontend -> Backend: Sends a petition with the credential
Backend -> MongoDB: Checks that user with that credentials match
alt Credentials match
MongoDB --> Backend: Returns information
Backend  --> Frontend: Gives information
Frontend --> Client: Successful login
else Credentials don't match
MongoDB --> Backend: Returns error message
Backend  --> Frontend: Returns error message
Frontend --> Client: Asks again for credentials showing error message
end
@enduml
----


=== Buy process

This view shows a request from a customer to buy a product from the catalog.

[plantuml,"BuyingProcess",png]
----
@startuml
actor Client
participant Frontend
participant Backend
database MongoDB
database SOLID
participant Shippo
participant Nodemailer
Client -> Frontend: Add products to cart
Frontend --> Client: Show products in the cart
Client -> Frontend: Delete products of the cart
Client -> Frontend: Checkout the products in the cart
Client -> Frontend: Enters Inrupt username
Frontend -> Backend: Sends petition with the username
Backend -> SOLID: Sends username
SOLID --> Backend: Returns the address of the user
Backend --> Frontend: Returns the address of the user
Frontend --> Client: Shows the address
Client -> Frontend: Requests for shipping costs
Frontend -> Backend: Petition to calculate shipping costs
Backend -> Shippo: Sends address calculate shipping costs
Shippo --> Backend: Returns shipping costs and estimated arrival day
Backend --> Frontend: Returns shipping costs and estimated arrival day
Frontend --> Client: Shows shipping costs and estimated arrival day
Client -> Frontend: Enter credit card data to pay
Frontend -> Backend: Sends petition to create order
Backend -> MongoDB: Creates the order
MongoDB --> Backend: Returns order details
Backend --> Frontend: Sends status code
Backend -> Nodemailer: Sends data of the order to send an email with the details
Nodemailer --> Client: Sends email with the details of the order
Frontend --> Client: Inform the customer of his order
@enduml
----


=== Sign up

This view shows the sign up process by a client.

[plantuml,"SignUpProcess",png]
----
@startuml
actor Client
participant Frontend
participant Backend
database MongoDB
Client -> Frontend: Enters username, email, password, confirm password and dni
Frontend -> Backend: Sends fields for validation
alt Validators pass
Backend -> MongoDB: Creates the user
MongoDB --> Backend: Sends the new user
Backend --> Frontend: Sends status code
Frontend --> Client: Successful registration, redirects to login
else Validators fail
Backend --> Frontend: Message with fails
Frontend --> Client: Notifies the error and requests fields again
end
@enduml
----

=== Modify products

This view shows how the administrator, after having logged in, will modify the catalog. The front-end makes a petition to the back-end by a petition and then the app connects to the database.

[plantuml,"AdminModify",png]
----
@startuml
actor Admin
participant Frontend
participant Backend
database MongoDB
Admin -> Frontend: Enters all the data from the product he wants to add, modify or delete
Frontend -> Backend: Sends the fields to update to the backend
Backend -> MongoDB: Modifies the database
Backend --> Frontend: Sends the product updated
Frontend --> Admin: Successful modification of the catalog
@enduml
----


=== View orders

This view shows how a client will obtain a list of all his orders.

[plantuml,"ClientOrders",png]
----
@startuml
actor Client
participant Frontend
participant Backend
database MongoDB
Client -> Frontend: Clicks the MyOrders option
Frontend -> Backend: Request for the orders of the client
Backend -> MongoDB: Ask for the list of orders of the client
MongoDB --> Backend: Get the list of orders
Backend --> Frontend: Returs the orders of the client
Frontend --> Client: Shows all of his orders
@enduml
----
