[[section-runtime-view]]

== Runtime View
 
.Contents

This section shows the main sequence diagrams between the users and the application.


=== Request

This view shows a request from a customer to view the product catalog. The web receives the request where it will access the database to get the list of products. Once obtained, it returns them to the customer.

[plantuml,"PresentationOfTheProductCatalog",png]
----
@startuml
actor Client
participant Frontend
participant Cloudinary
participant Backend
database MongoDB
Client -> Frontend: Access to products catalog
Frontend -> Backend: Request product list
Backend -> MongoDB: Ask for the list of products
MongoDB --> Backend: Get the list of products
Backend --> Frontend: Send the list of products
Frontend -> Cloudinary: Request for the image of the product
Cloudinary --> Frontend: Sends the image of the product
Frontend --> Client: Get the catalog
@enduml
----


=== Login

This view shows the login process. The website receives the user's credentials, and after a back-end petition the credentials will be verified and the user will be allowed to buy products.

[plantuml,"LoginView",png]
----
@startuml
actor Client
participant Frontend
participant Backend
database MongoDB
Client -> Frontend: Enter credentials
Frontend -> Backend: Sends a petition with the credential
Backend -> MongoDB: Checks that user with that credentials match
alt Credentials match
MongoDB --> Backend: Returns information
Backend  --> Frontend: Gives information
Frontend --> Client: Successful login
else Credentials don't match
MongoDB --> Backend: Returns error message
Backend  --> Frontend: Returns error message
Frontend --> Client: Asks again for credentials showing error message
end
@enduml
----


=== Buy process

This view shows a request from a customer to buy a product from the catalog.

[plantuml,"BuyingProcess",png]
----
@startuml
actor Client
participant DeDe
database MongoDb
database Solid
Client -> DeDe: Add products to cart
DeDe -> MongoDb: Save the products of client
Client -> DeDe: Delete products of the cart
DeDe -> MongoDb: Restore products
Client -> DeDe: Checkout the products in the cart
DeDe -> Solid: Ask for the data of client
Solid --> DeDe: Personal data of client
DeDe -> MongoDb: Save purchase data
DeDe --> Client: Inform the customer of his purchase
@enduml
----


=== Sign up

This view shows the sign up process by a customer.

[plantuml,"SignUpProcess",png]
----
@startuml
actor Client
participant DeDe
database MongoDb
database Solid
Client -> DeDe: Request store registration
DeDe -> Client: Request for Pod access
DeDe -> Solid: Pod Access
Solid --> DeDe: Return of personal information
DeDe -> Client: User and password request
Client --> DeDe: User and password return
DeDe -> MongoDb: Save credentials
DeDe --> Client: Successful registration
@enduml
----

=== Modify products

This view shows how the administrator, after having logged in, will modify the catalog. The front-end makes a petition to the back-end by a petition and then the app connects to the database by mongoose.

[plantuml,"AdminModify",png]
----
@startuml
actor Admin
participant DeDe
participant Axios
participant Mongoose
database MongoDb
Admin -> DeDe: Enters all the data from the product he wants to add, modify or delete
DeDe --> Axios: Connects front-end to back-end by a petition
DeDe -> Mongoose: Verifies that the user is an administrator, validates the data
Mongoose --> MongoDb: Modifies the database
DeDe --> Admin: Successful modification of the catalog

@enduml
----


=== View orders

This view shows how a client will obtain a list of all his orders.

[plantuml,"ClientOrders",png]
----
@startuml
actor Client
participant DeDe
database MongoDb
Client -> DeDe: Request his orders
DeDe -> MongoDb: Ask for the list of orders of the client
MongoDb --> DeDe: Get the list of orders
DeDe --> Client: Gets all of his orders
@enduml
----
