[[section-runtime-view]]

== Runtime View
 
.Contents

This section shows the main sequence diagrams between the users and the application.


=== Request

This view shows a request from a customer to view the product catalog. The web receives the request where it will access the database to get the list of products. Once obtained, it returns them to the customer.

[plantuml,"PresentationOfTheProductCatalog",png]
----
@startuml
actor Client
participant DeDe
database MongoDb
Client -> DeDe: Request product catalog
DeDe -> MongoDb: Ask for the list of products
MongoDb --> DeDe: Get the list of products
DeDe --> Client: Get the catalog
@enduml
----


=== Login

This view shows the administrator login. The website receives the admin's credentials, and after verification of the information allows the admin to add, delete and update the desired products.

[plantuml,"AdminView",png]
----
@startuml
actor Admin
participant DeDe
database MongoDb
Admin -> DeDe: Enter credentials
DeDe -> MongoDb: Verify the information entered
DeDe --> Admin: Successful login
@enduml
----


=== Buy process

This view shows a request from a customer to buy a product from the catalog.

[plantuml,"BuyingProcess",png]
----
@startuml
actor Client
participant DeDe
database MongoDb
database Solid
Client -> DeDe: Add products to cart
DeDe -> MongoDb: Save the products of client
Client -> DeDe: Delete products of the cart
DeDe -> MongoDb: Restore products
Client -> DeDe: Checkout the products in the cart
DeDe -> Solid: Ask for the data of client
Solid --> DeDe: Personal data of client
DeDe -> MongoDb: Save purchase data
DeDe --> Client: Inform the customer of his purchase
@enduml
----


=== Sign up

This view shows the sign up process by a customer.

[plantuml,"SignUpProcess",png]
----
@startuml
actor Client
participant DeDe
database MongoDb
database Solid
Client -> DeDe: Request store registration
DeDe -> Client: Request for Pod access
DeDe -> Solid: Pod Access
Solid --> DeDe: Return of personal information
DeDe -> Client: User and password request
Client --> DeDe: User and password return
DeDe -> MongoDb: Save credentials
DeDe --> Client: Successful registration
@enduml
----

=== Add products

This view shows how the administrator will add a product to the catalog.

[plantuml,"AdminAdd",png]
----
@startuml
actor Admin
participant DeDe
database MongoDb
Admin -> DeDe: Enters all the data from the new product
DeDe -> MongoDb: Verifies that the user is an administrator, validates the data and chages the database
DeDe --> Admin: Successful addition of the product
@enduml
----


=== View orders

This view shows how a client will obtain a list of all his orders.

[plantuml,"ClientOrders",png]
----
@startuml
actor Client
participant DeDe
database MongoDb
Client -> DeDe: Request his orders
DeDe -> MongoDb: Ask for the list of orders of the client
MongoDb --> DeDe: Get the list of orders
DeDe --> Client: Gets all of his orders
@enduml
----
