[[section-technical-risks]]
== Risks and Technical Debts


[role="arc42help"]
****
.Contents
A list of identified technical risks or technical debts, ordered by priority

.Motivation
“Risk management is project management for grown-ups” (Tim Lister, Atlantic Systems Guild.) 

This should be your motto for systematic detection and evaluation of risks and technical debts in the architecture, which will be needed by management stakeholders (e.g. project managers, product owners) as part of the overall risk analysis and measurement planning.

.Form
List of risks and/or technical debts, probably including suggested measures to minimize, mitigate or avoid risks or reduce technical debts.
****

[options="header",cols="1,2"]
|===
|Riesgo|Soluciones
| Falta de conocimiento de react | Consultar los foros de react
| Falta de conocimiento de solid | Consultar los foros de solid
| Abandono por parte de algun miembro | Realizar actas periodicas
| Falta de tiempo respecto a entregas | Marcar unas pautas para un avance regular y estable
| Malentendidos en los requisitos de la aplicacion | Aclarar los requisitos con el profesor
| Problemas de mergeos en git | Marcar unas pautas para un mergeo estable
|===
